pages:
  image: node:14-alpine
  stage: deploy
  tags:
    - pages
  variables:
    NODE_ENV: production
  script:
    - npm ci --production=false # we need the dev dependencies for the build
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    # optionally, you can activate gzip support with the following line:
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
