branches:
  - main
  - name: beta
    prerelease: true
baseBranch: main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
        - path: "release.zip"
